import Foundation

struct WasmEntry: Identifiable {
  let displayName: String
  let description: String
  let resourceName: String

  var id: String { displayName }

  static let all: [WasmEntry] = [
    WasmEntry(
      displayName: "blink-loop.wasm",
      description: "Blinks 3 times",
      resourceName: "blink-loop"),
    WasmEntry(
      displayName: "blink-loop2.wasm",
      description: "Blinks 5 times",
      resourceName: "blink-loop2"),
    WasmEntry(
      displayName: "gpio-blink-swift.wasm",
      description: "Generated by Swift",
      resourceName: "gpio-blink-swift"),
    WasmEntry(
      displayName: "i32-add.wasm",
      description: "Calls add(3, 4) and prints result via UART",
      resourceName: "i32-add"),
  ]
}
